version: '3.7'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
      - SEARXNG_SECRET=changeme-$(openssl rand -hex 16)
    restart: unless-stopped
    networks:
      - searxng-network

networks:
  searxng-network:
    driver: bridge
